import type { Metadata } from 'next'
import './globals.css'
import { AI } from '@/app/actions/provider'
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body>
    <AI>
      {children}
    </AI>
    </body>
    </html>
  )
}
